In [8]:
import numpy as np
np.random.seed(3)
from keras.preprocessing.image import ImageDataGenerator

In [9]:
train_datagen = ImageDataGenerator(rescale=1./255)
                                   

train_generator = train_datagen.flow_from_directory(
        'C:/Users/Owner2/Desktop/deep/train',
        target_size=(150, 150),
        batch_size=64,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        'C:/Users/Owner2/Desktop/deep/test',
        target_size=(150, 150),    
        batch_size=16,
        class_mode='categorical')

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D

Found 6400 images belonging to 8 classes.
Found 1600 images belonging to 8 classes.


In [10]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D

from keras.layers import Dropout

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(150,150,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(8, activation='softmax'))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 148, 148, 32)      896       
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 146, 146, 64)      18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 73, 73, 64)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 341056)            0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               43655296  
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 1032      
Total params: 43,675,720
Trainable params: 43,675,720
Non-trainable params: 0
________________________________________________________________

In [11]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [12]:
# 모델 학습시키기
model.fit_generator(
        train_generator,
        steps_per_epoch=100,
        epochs=100,
        validation_data=test_generator,
        validation_steps=50)

Epoch 1/100
100/100 [==============================] - 94s 943ms/step - loss: 1.8208 - acc: 0.5739 - val_loss: 0.6768 - val_acc: 0.6825
Epoch 2/100
100/100 [==============================] - 85s 846ms/step - loss: 0.5952 - acc: 0.7331 - val_loss: 0.7133 - val_acc: 0.7025
Epoch 3/100
100/100 [==============================] - 84s 843ms/step - loss: 0.4381 - acc: 0.8173 - val_loss: 0.6216 - val_acc: 0.7188
Epoch 4/100
100/100 [==============================] - 85s 848ms/step - loss: 0.2784 - acc: 0.8947 - val_loss: 0.6933 - val_acc: 0.7250
Epoch 5/100
100/100 [==============================] - 85s 848ms/step - loss: 0.1642 - acc: 0.9408 - val_loss: 0.8587 - val_acc: 0.7075
Epoch 6/100
100/100 [==============================] - 84s 842ms/step - loss: 0.1113 - acc: 0.9627 - val_loss: 0.8449 - val_acc: 0.7275
Epoch 7/100
100/100 [==============================] - 85s 847ms/step - loss: 0.0561 - acc: 0.9848 - val_loss: 1.0225 - val_acc: 0.7288
Epoch 8/100
100/100 [===========================

Epoch 61/100
100/100 [==============================] - 85s 851ms/step - loss: 0.0025 - acc: 0.9998 - val_loss: 1.9058 - val_acc: 0.7300
Epoch 62/100
100/100 [==============================] - 85s 846ms/step - loss: 0.0025 - acc: 0.9998 - val_loss: 1.9632 - val_acc: 0.7150
Epoch 63/100
100/100 [==============================] - 87s 868ms/step - loss: 0.0025 - acc: 0.9998 - val_loss: 1.8200 - val_acc: 0.7475
Epoch 64/100
100/100 [==============================] - 85s 849ms/step - loss: 0.0025 - acc: 0.9998 - val_loss: 2.0813 - val_acc: 0.6963
Epoch 65/100
100/100 [==============================] - 86s 864ms/step - loss: 0.0025 - acc: 0.9998 - val_loss: 1.8125 - val_acc: 0.7400
Epoch 66/100
100/100 [==============================] - 86s 862ms/step - loss: 0.0025 - acc: 0.9998 - val_loss: 2.0942 - val_acc: 0.7037
Epoch 67/100
100/100 [==============================] - 86s 859ms/step - loss: 0.0025 - acc: 0.9998 - val_loss: 1.9782 - val_acc: 0.7087
Epoch 68/100
100/100 [===================

In [ ]:
"""#그래프로 학습내용 확인하기
plt.figure(figsize=(12, 12))
plt.subplot(1, 2, 1)
plt.plot(hist.history['loss'])
plt.title("훈련 중 비용함수 그래프")
plt.ylabel("비용함수 값")
plt.subplot(1, 2, 2)
plt.title("훈련 중 성능지표 그래프")
plt.ylabel("성능지표 값")
plt.plot(hist.history['accuracy'], 'b-', label="학습 성능")
plt.plot(hist.history['val_accuracy'], 'r:', label="검증 성능")
plt.legend()
plt.tight_layout()
plt.show()"""

In [24]:
# 모델 평가하기
print("-- Evaluate --")

scores = model.evaluate_generator(
            test_generator, 
            steps = 5)

print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
acc: 75.00%


In [25]:
# 모델 예측하기
print("-- Predict --")

prediction = model.predict_generator(
            test_generator, 
            steps = 5)

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

print(prediction)


-- Predict --
[[0.998 0.002 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000]
 [0.000 0.000 0.996 0.000 0.000 0.004 0.000 0.000]
 [0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.003 0.000 0.000 0.997 0.000]
 [0.000 0.000 0.000 0.000 0.925 0.075 0.000 0.000]
 [0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000]
 [0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000]
 [0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.972 0.000 0.000 0.028 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.006 0.994]
 [0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000]
 [0.132 0.868 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.023 0.977 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 1.000 0.0

In [29]:
#예측값 중 가장 높은 값 찾기
np.argmax(prediction)

76