In [1]:
import numpy as np
np.random.seed(8)
from keras.preprocessing.image import ImageDataGenerator


Using TensorFlow backend.


In [2]:
train_datagen = ImageDataGenerator(rescale=1./255)
                                   

train_generator = train_datagen.flow_from_directory(
        'C:/Users/Owner2/Desktop/deep/train',
        target_size=(150, 150),
        batch_size=64,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        'C:/Users/Owner2/Desktop/deep/test',
        target_size=(150, 150),    
        batch_size=16,
        class_mode='categorical')

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D

Found 6400 images belonging to 8 classes.
Found 1600 images belonging to 8 classes.


In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D

from keras.layers import Dropout

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(150,150,3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(8, activation='softmax'))

model.summary()

W1128 05:36:05.846275 12008 deprecation_wrapper.py:119] From C:\Users\Owner2\Anaconda3\envs\keras2\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W1128 05:36:05.862584 12008 deprecation_wrapper.py:119] From C:\Users\Owner2\Anaconda3\envs\keras2\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W1128 05:36:05.865584 12008 deprecation_wrapper.py:119] From C:\Users\Owner2\Anaconda3\envs\keras2\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W1128 05:36:05.882596 12008 deprecation_wrapper.py:119] From C:\Users\Owner2\Anaconda3\envs\keras2\lib\site-packages\keras\backend\tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 148, 148, 32)      896       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 74, 74, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 72, 72, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 36, 36, 64)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 34, 34, 128)       73856     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 17, 17, 128)       0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 36992)             0         
__________

In [4]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

W1128 05:36:13.932813 12008 deprecation_wrapper.py:119] From C:\Users\Owner2\Anaconda3\envs\keras2\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W1128 05:36:13.958921 12008 deprecation_wrapper.py:119] From C:\Users\Owner2\Anaconda3\envs\keras2\lib\site-packages\keras\backend\tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [5]:
# 모델 학습시키기
model.fit_generator(
        train_generator,
        steps_per_epoch=100,
        epochs=50,
        validation_data=test_generator,
        validation_steps=50)

W1128 05:36:24.389902 12008 deprecation.py:323] From C:\Users\Owner2\Anaconda3\envs\keras2\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W1128 05:36:24.523208 12008 deprecation_wrapper.py:119] From C:\Users\Owner2\Anaconda3\envs\keras2\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/50
100/100 [==============================] - 95s 947ms/step - loss: 0.9663 - acc: 0.5952 - val_loss: 0.6956 - val_acc: 0.6625
Epoch 2/50
100/100 [==============================] - 85s 850ms/step - loss: 0.6407 - acc: 0.7089 - val_loss: 0.6807 - val_acc: 0.6887
Epoch 3/50
100/100 [==============================] - 86s 859ms/step - loss: 0.5639 - acc: 0.7478 - val_loss: 0.6475 - val_acc: 0.6887
Epoch 4/50
100/100 [==============================] - 85s 853ms/step - loss: 0.4980 - acc: 0.7827 - val_loss: 0.6391 - val_acc: 0.7450
Epoch 5/50
100/100 [==============================] - 85s 854ms/step - loss: 0.4284 - acc: 0.8156 - val_loss: 0.5893 - val_acc: 0.7612
Epoch 6/50
100/100 [==============================] - 86s 859ms/step - loss: 0.3648 - acc: 0.8466 - val_loss: 0.6385 - val_acc: 0.7350
Epoch 7/50
100/100 [==============================] - 85s 855ms/step - loss: 0.2803 - acc: 0.8888 - val_loss: 0.6507 - val_acc: 0.7425
Epoch 8/50
100/100 [==============================] - 8

In [6]:
"""#그래프로 학습내용 확인하기
plt.figure(figsize=(12, 12))
plt.subplot(1, 2, 1)
plt.plot(hist.history['loss'])
plt.title("훈련 중 비용함수 그래프")
plt.ylabel("비용함수 값")
plt.subplot(1, 2, 2)
plt.title("훈련 중 성능지표 그래프")
plt.ylabel("성능지표 값")
plt.plot(hist.history['accuracy'], 'b-', label="학습 성능")
plt.plot(hist.history['val_accuracy'], 'r:', label="검증 성능")
plt.legend()
plt.tight_layout()
plt.show()"""

'#그래프로 학습내용 확인하기\nplt.figure(figsize=(12, 12))\nplt.subplot(1, 2, 1)\nplt.plot(hist.history[\'loss\'])\nplt.title("훈련 중 비용함수 그래프")\nplt.ylabel("비용함수 값")\nplt.subplot(1, 2, 2)\nplt.title("훈련 중 성능지표 그래프")\nplt.ylabel("성능지표 값")\nplt.plot(hist.history[\'accuracy\'], \'b-\', label="학습 성능")\nplt.plot(hist.history[\'val_accuracy\'], \'r:\', label="검증 성능")\nplt.legend()\nplt.tight_layout()\nplt.show()'

In [17]:
# 모델 평가하기
print("-- Evaluate --")

scores = model.evaluate_generator(
            test_generator, 
            steps = 5)

print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
acc: 82.50%


In [18]:
# 모델 예측하기
print("-- Predict --")

prediction = model.predict_generator(
            test_generator, 
            steps = 5)

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

print(prediction)


-- Predict --
[[0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000]
 [0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.001 0.000 0.000 0.999 0.000 0.000]
 [0.012 0.988 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.379 0.621]
 [1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.999 0.001 0.000 0.000 0.000 0.000 0.000 0.000]
 [1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.780 0.220 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000]
 [0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000]
 [0.000 0.000 0.986 0.000 0.014 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.892 0.108]
 [0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000]
 [0.000 0.000 0.0

In [19]:
#예측값 중 가장 높은 값 찾기
np.argmax(prediction)

2

In [20]:
model.save('endoscope_model_ver.82.50.h5')